
if(Memory.partDefinitions === undefined) {
    Memory.partDefinitions = {
        run: [
            [CARRY,MOVE,CARRY,MOVE]],
        rep: [
            [CARRY,MOVE,WORK,WORK,WORK]],
        med: [
            [HEAL,HEAL,HEAL,HEAL,MOVE]],
        ext: [
            [MOVE,CARRY,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK]],
        bld: [
            [MOVE,CARRY,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK],
            [MOVE,CARRY,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK]], 
        min: [
            [MOVE,WORK,WORK,WORK,WORK,],
            [MOVE,WORK,WORK,WORK,WORK,WORK],
            [MOVE,WORK,WORK,WORK,WORK,WORK,WORK],
            [MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK],
            [MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK],
            [MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK],
            [MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK]],
        grd: [
            [TOUGH,TOUGH,MOVE,RANGED_ATTACK,MOVE],
            [TOUGH,TOUGH,TOUGH,MOVE,RANGED_ATTACK,MOVE],
            [TOUGH,TOUGH,TOUGH,MOVE,RANGED_ATTACK,RANGED_ATTACK,MOVE],
            [TOUGH,TOUGH,TOUGH,MOVE,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,MOVE],
            [TOUGH,TOUGH,TOUGH,MOVE,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,MOVE],
            [TOUGH,TOUGH,TOUGH,MOVE,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,MOVE],
            [TOUGH,TOUGH,TOUGH,MOVE,MOVE,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,MOVE],
            [TOUGH,TOUGH,TOUGH,MOVE,MOVE,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,MOVE]]
    };
}

var roomManager = require('roomManager');
var helper = require('helper');

for(var name in Game.rooms) {
    var roomObj = Game.rooms[name];
    //var flag = 0; // Nothing unusual, not sure if it will ever be used...
    roomManager(roomObj, helper);
}
